### ISSUE TITLE
Phoenix ELN Server Package

### ISSUE THREAD

**Issue by chris9672** [abrechts/Phoenix-ELN#14]
A lot of things on this project are not really functional yet. The link that is supposed to lead to Phoenix ELN Server Package generates a 404 error coz it is not available and when you download the phoenix-eln-help.github.io, the index.html greets you with
"Ssdsdsdsds

Dsdsdsdsds

Dsdsdsdsds..."

**Comment by abrechts** [comment]
The Phoenix-ELN Wiki and the readme file is the current 'official' source of the help documentation on the Phoenix ELN project page. Don't worry about Phoenix-eln-help.github.io, since it's work in progress to be linked later for consumption by the first non-beta Phoenix ELN release. And please let me know about the many other things you mentioned not to be working yet, to get them fixed if possible. Thanks.
