### ISSUE TITLE
Renaming experiments

### ISSUE THREAD

**Issue by msellstedt** [abrechts/Phoenix-ELN#20]
Hello,
I would like to be able to name/rename experiments at my own choice. Is that possible?

I also would like to know if there is any convienient way to handle risk assessments for each experiment. - It would for instance help if risk phrases were saved and easily viewed for chemicals previously used in other experiments or present in the substance database.

**Comment by abrechts** [comment]
Thanks for your contribution, which you added to the Issues section. However, you are not describing an issue, i.e. a bug. Please place such contributions to the Discussions section in the future. Thanks!

To answer your question about experiment renaming anyway: No, renaming experiments is definitely not possible. Experiments must have a unique identifier including an uninterrupted incremental suffix by design. This allows unique experiment identification for yourself and within the context an organization.

Your idea about attaching e.g. materials safety data sheets to materials in the materials database sounds interesting. Could you therefore please place this proposal separately into Discussions / Feature Proposals assessing it further. Thanks.

**Comment by abrechts** [comment]
Your idea about attaching safety documents was implemented in the v.2.4.0 release :-).
